### ISSUE TITLE
Beta Roadmap

### ISSUE THREAD

**Issue by colmtuite** [radix-ui/primitives#371]
### General

- [ ] Ensure touch support is good across all primitives.
- [ ] Test all primitives rigorously with Stitches and SC, raising issues along the way.
- [ ] Complete any unfinished features (like the positioning logic for DropdownMenu raised in the design tool).

### Docs

- [ ] Add UI to docs for cycling through docs versions. (Pedro)
- [ ] Add examples to relevant primitives showing how to wrap them in good consumer APIs. (Pedro)
- [ ] Add tutorial videos for each primitive. (Pedro)
- [ ] Add new top-level "Composition" section, mentioning `forwardRef` etc. (Chance)

### New Primitives

Loosely in order of priority.

- [ ] Submenu (Benoît)
- [ ] Select (Benoît)
- [ ] Menubar (Benoît)
- [ ] ToggleButtonGroup (Chance)
- [ ] Toast (Chance)
- [ ] HoverCard
- [ ] Carousel
- [ ] Toolbar

**Comment by colmtuite** [comment]
@jjenzz @benoitgrelard @chaance @peduarte 

I've put together this roadmap for Primitives, to serve as a guide for what to work toward for the beta release.

Take a look and let me know if you have any questions, or if there are tasks you'd like to add/remove.

**Comment by chaance** [comment]
Per our conversation, closing this and moved to Discussions: https://github.com/radix-ui/primitives/discussions/375

I am going to open new issues for action items based on the roadmap.
